
package org.example.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AvailabilityServiceService", targetNamespace = "http://service.example.org/", wsdlLocation = "http://127.0.0.1:8081/availability?wsdl")
public class AvailabilityServiceService
    extends Service
{

    private final static URL AVAILABILITYSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException AVAILABILITYSERVICESERVICE_EXCEPTION;
    private final static QName AVAILABILITYSERVICESERVICE_QNAME = new QName("http://service.example.org/", "AvailabilityServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8081/availability?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AVAILABILITYSERVICESERVICE_WSDL_LOCATION = url;
        AVAILABILITYSERVICESERVICE_EXCEPTION = e;
    }

    public AvailabilityServiceService() {
        super(__getWsdlLocation(), AVAILABILITYSERVICESERVICE_QNAME);
    }

    public AvailabilityServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AVAILABILITYSERVICESERVICE_QNAME, features);
    }

    public AvailabilityServiceService(URL wsdlLocation) {
        super(wsdlLocation, AVAILABILITYSERVICESERVICE_QNAME);
    }

    public AvailabilityServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AVAILABILITYSERVICESERVICE_QNAME, features);
    }

    public AvailabilityServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AvailabilityServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IAvailabilityService
     */
    @WebEndpoint(name = "AvailabilityServicePort")
    public IAvailabilityService getAvailabilityServicePort() {
        return super.getPort(new QName("http://service.example.org/", "AvailabilityServicePort"), IAvailabilityService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAvailabilityService
     */
    @WebEndpoint(name = "AvailabilityServicePort")
    public IAvailabilityService getAvailabilityServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.example.org/", "AvailabilityServicePort"), IAvailabilityService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AVAILABILITYSERVICESERVICE_EXCEPTION!= null) {
            throw AVAILABILITYSERVICESERVICE_EXCEPTION;
        }
        return AVAILABILITYSERVICESERVICE_WSDL_LOCATION;
    }

}
