
package org.example.client;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IAvailabilityService", targetNamespace = "http://service.example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IAvailabilityService {


    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<org.example.client.IsBookForReadingRoomOnlyResponse>
     */
    @WebMethod(operationName = "isBookForReadingRoomOnly")
    @RequestWrapper(localName = "isBookForReadingRoomOnly", targetNamespace = "http://service.example.org/", className = "org.example.client.IsBookForReadingRoomOnly")
    @ResponseWrapper(localName = "isBookForReadingRoomOnlyResponse", targetNamespace = "http://service.example.org/", className = "org.example.client.IsBookForReadingRoomOnlyResponse")
    public Response<IsBookForReadingRoomOnlyResponse> isBookForReadingRoomOnlyAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Book arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "isBookForReadingRoomOnly")
    @RequestWrapper(localName = "isBookForReadingRoomOnly", targetNamespace = "http://service.example.org/", className = "org.example.client.IsBookForReadingRoomOnly")
    @ResponseWrapper(localName = "isBookForReadingRoomOnlyResponse", targetNamespace = "http://service.example.org/", className = "org.example.client.IsBookForReadingRoomOnlyResponse")
    public Future<?> isBookForReadingRoomOnlyAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Book arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<IsBookForReadingRoomOnlyResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isBookForReadingRoomOnly", targetNamespace = "http://service.example.org/", className = "org.example.client.IsBookForReadingRoomOnly")
    @ResponseWrapper(localName = "isBookForReadingRoomOnlyResponse", targetNamespace = "http://service.example.org/", className = "org.example.client.IsBookForReadingRoomOnlyResponse")
    @Action(input = "http://service.example.org/IAvailabilityService/isBookForReadingRoomOnlyRequest", output = "http://service.example.org/IAvailabilityService/isBookForReadingRoomOnlyResponse")
    public boolean isBookForReadingRoomOnly(
        @WebParam(name = "arg0", targetNamespace = "")
        Book arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<org.example.client.IsBookAvailableResponse>
     */
    @WebMethod(operationName = "isBookAvailable")
    @RequestWrapper(localName = "isBookAvailable", targetNamespace = "http://service.example.org/", className = "org.example.client.IsBookAvailable")
    @ResponseWrapper(localName = "isBookAvailableResponse", targetNamespace = "http://service.example.org/", className = "org.example.client.IsBookAvailableResponse")
    public Response<IsBookAvailableResponse> isBookAvailableAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Book arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "isBookAvailable")
    @RequestWrapper(localName = "isBookAvailable", targetNamespace = "http://service.example.org/", className = "org.example.client.IsBookAvailable")
    @ResponseWrapper(localName = "isBookAvailableResponse", targetNamespace = "http://service.example.org/", className = "org.example.client.IsBookAvailableResponse")
    public Future<?> isBookAvailableAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Book arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<IsBookAvailableResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isBookAvailable", targetNamespace = "http://service.example.org/", className = "org.example.client.IsBookAvailable")
    @ResponseWrapper(localName = "isBookAvailableResponse", targetNamespace = "http://service.example.org/", className = "org.example.client.IsBookAvailableResponse")
    @Action(input = "http://service.example.org/IAvailabilityService/isBookAvailableRequest", output = "http://service.example.org/IAvailabilityService/isBookAvailableResponse")
    public boolean isBookAvailable(
        @WebParam(name = "arg0", targetNamespace = "")
        Book arg0);

}
