
package org.example.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RentalServiceService", targetNamespace = "http://service.example.org/", wsdlLocation = "http://127.0.0.1:8081/rental?wsdl")
public class RentalServiceService
    extends Service
{

    private final static URL RENTALSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException RENTALSERVICESERVICE_EXCEPTION;
    private final static QName RENTALSERVICESERVICE_QNAME = new QName("http://service.example.org/", "RentalServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8081/rental?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RENTALSERVICESERVICE_WSDL_LOCATION = url;
        RENTALSERVICESERVICE_EXCEPTION = e;
    }

    public RentalServiceService() {
        super(__getWsdlLocation(), RENTALSERVICESERVICE_QNAME);
    }

    public RentalServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RENTALSERVICESERVICE_QNAME, features);
    }

    public RentalServiceService(URL wsdlLocation) {
        super(wsdlLocation, RENTALSERVICESERVICE_QNAME);
    }

    public RentalServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RENTALSERVICESERVICE_QNAME, features);
    }

    public RentalServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RentalServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IRentalService
     */
    @WebEndpoint(name = "RentalServicePort")
    public IRentalService getRentalServicePort() {
        return super.getPort(new QName("http://service.example.org/", "RentalServicePort"), IRentalService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IRentalService
     */
    @WebEndpoint(name = "RentalServicePort")
    public IRentalService getRentalServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.example.org/", "RentalServicePort"), IRentalService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RENTALSERVICESERVICE_EXCEPTION!= null) {
            throw RENTALSERVICESERVICE_EXCEPTION;
        }
        return RENTALSERVICESERVICE_WSDL_LOCATION;
    }

}
